module: SpotifyWebAPI

skip_undocumented: true

exclude:
  - "Sources/SpotifyWebAPI/URLExtensions/*"
  - "Sources/SpotifyWebAPI/Other/ApproximateEquality.swift"
  - "Sources/SpotifyWebAPI/Other/CodingExtensions.swift"
  - "Sources/SpotifyWebAPI/Other/DateExtensions.swift"
  - "Sources/SpotifyWebAPI/Other/DateFormatterExtensions.swift"
  - "Sources/SpotifyWebAPI/Other/MiscellaneousUtilities.swift"
  
custom_categories:

  - name: SpotifyAPI
    children:
    - SpotifyAPI
    
  - name: Authorization
    children:
    - AuthorizationCodeFlowPKCEManager
    - AuthorizationCodeFlowManager
    - AuthorizationCodeFlowManagerBase
    - ClientCredentialsFlowManager
    - AuthorizationCodeFlowBackendManager
    - AuthorizationCodeFlowPKCEBackendManager
    - ClientCredentialsFlowBackendManager
    - Scope
    - SpotifyAuthorizationManager
    - SpotifyScopeAuthorizationManager

  - name: Authorization Backends
    children:
    - AuthorizationCodeFlowBackend
    - AuthorizationCodeFlowClientBackend
    - AuthorizationCodeFlowProxyBackend
    - AuthorizationCodeFlowPKCEBackend
    - AuthorizationCodeFlowPKCEClientBackend
    - AuthorizationCodeFlowPKCEProxyBackend
    - ClientCredentialsFlowBackend
    - ClientCredentialsFlowClientBackend
    - ClientCredentialsFlowProxyBackend

  - name: Authentication Objects
    children:
    - AuthInfo
    - ClientCredentialsTokensRequest
    - TokensRequest
    - ProxyTokensRequest
    - RefreshTokensRequest
    - PKCETokensRequest
    - ProxyPKCETokensRequest
    - PKCERefreshTokensRequest
    - ProxyPKCERefreshTokensRequest

  - name: Errors
    children:
    - SpotifyError
    - SpotifyPlayerError
    - SpotifyGeneralError
    - RateLimitedError
    - SpotifyAuthenticationError
    - SpotifyAuthorizationError
    - SpotifyDecodingError
    
  - name: Publisher Extensions
    children:
    - Publisher
    - Error
    - decodeSpotifyErrors(data:httpURLResponse:)
    - decodeSpotifyObject(data:httpURLResponse:responseType:)
    
  - name: Protocols
    children:
    - Paginated
    - SpotifyURIConvertible

  - name: Media Objects
    children:
    - Album
    - Artist
    - Track
    - Episode
    - Show
    
  - name: Playlist Objects
    children:
    - Playlist
    - PlaylistItem
    - PlaylistItemContainer
    - PlaylistItemsReference
    - PlaylistDetails
    - ReorderPlaylistItems
    - URIWithPositions
    - URIsWithPositionsContainer
    - URIsContainer
    - URIsDictWithInsertionIndex
      
  - name: Player Objects
    children:
    - Device
    - DeviceType
    - CurrentlyPlayingContext
    - SpotifyContext
    - PlaybackActions
    - PlayHistory
    - ResumePoint
    - RepeatMode
    - PlaybackRequest
    - TimeReference
    
  - name: Audio Analysis Objects
    children:
    - AudioAnalysis
    - AudioFeatures
    - Section
    - Segment
    - SpotifyTimeInterval
    
  - name: Type Aliases
    children:
    - PlaylistTracks
    - PlaylistItems
    
  - name: Other Objects
    children:
    - PagingObject
    - SavedItem
    - SearchResult
    - SpotifyImage
    - SpotifyUser
    - Followers
    - CursorPagingObject
    - SpotifyCursor
    - TrackLink
    - SpotifyCopyright
    - AlbumType
    - TimeRange
    - FeaturedPlaylists
    - NewAlbumReleases
    - RecommendationSeed
    - RecommendationsResponse
    - TrackAttributes
    - AttributeRange
    - SpotifyCategory
    
